//
// Created by Linghan Xing on 9/28/18.
//

#ifndef ISIS_LAMPORT_MESSAGES_H
#define ISIS_LAMPORT_MESSAGES_H

#include <stdint.h>

typedef struct {
    uint32_t type; // must be equal to 1
    uint32_t sender; // sender's id
    uint32_t msg_id; // the identifier of the message generated by sender
    uint32_t data;
} DataMessage;

typedef struct {
    uint32_t type; // must be equal to 2
    uint32_t sender; // the sender of the DataMessage
    uint32_t msg_id; // the identifier of the DataMessage generated by sender
    uint32_t proposed_seq; // the proposed sequence number
    uint32_t proposer; // the process id of the proposer
} AckMessage;

typedef struct {
    uint32_t type; // must be 3
    uint32_t sender; // the sender of the DataMessage
    // the identifier of the DataMessage generated by sender
    uint32_t msg_id;
    uint32_t final_seq; // the final sequence number selected
    // the process id of the proposer who proposed the final seq
    uint32_t final_seq_proposer;
} SqeMessage;

#endif //ISIS_LAMPORT_MESSAGES_H
