//
// Created by Linghan Xing on 10/3/18.
//
#include "messages.h"
#include <arpa/inet.h>

//typedef struct {
//    uint32_t type; // must be equal to 1
//    uint32_t sender; // sender's id
//    uint32_t msg_id; // the identifier of the message generated by sender
//    uint32_t data;
//} DataMessage;

DataMessage* hton(DataMessage* msg) {
    msg -> type = htonl(msg->type);
    msg -> sender = htonl(msg -> sender);
    msg -> msg_id = htonl(msg -> msg_id);
    msg -> data = htonl(msg -> data);

    return msg;
}


